version: '3.8'
services:
  aspnet-be:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - '8000:80'
    depends_on:
      - db
    environment: 
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=degustai;User Id=postgres;Password=postgres;

  db:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=degustai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: